dataset: CAVIAR-o # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-o/vm_mixture'
data_path: 'data/CAVIAR-o.pkl.gz'
experiment_name: 'vm_mixture'
canonical_split: True
model_type: vm_mixture
loss_type: vm_likelihood
fixed_kappa_value: 10
n_epochs: 1000
val_check_period: 128 #32
patience: 1000
n_trials: 50
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
batch_size: 8
n_components: 5
learning_rate: 0.0001
beta1: 0.9
beta2: 0.999
epsilon: 1.0e-8
conv_dropout: 0.2
fc_dropout: 0.5
vgg_fc_layer_size: 512
cvae_fc_layer_size: 512