dataset: CAVIAR-o # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-o/cvae'
data_path: 'data/CAVIAR-o.pkl.gz'
experiment_name: 'vggbit_cvae'
canonical_split: True
model_type: cvae
n_epochs: 1000
val_check_period: 128 #32
patience: 1000
n_trials: 5
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
n_hidden_units: 4 #8
batch_size: 32
learning_rate: 0.001
beta1: 0.74
beta2: 0.9995
epsilon: 8.3492744563834517e-07
conv_dropout: 0.244
fc_dropout: 0.436
vgg_fc_layer_size: 190
cvae_fc_layer_size: 383