dataset: CAVIAR-o # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-o'
data_path: 'data//CAVIAR-o.pkl.gz'
loss: vm_likelihood # possible choices : cosine, von_mises, mad, vm_likelihood
experiment_name: 'vggbit_likelihood'
canonical_split: True
predict_kappa: True
fixed_kappa_value: 10.0
n_epochs: 50
val_check_period: 32
conv_dropout: 0.2
fc_dropout: 0.5
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters
n_trials: 50