dataset: CAVIAR-o # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-o/cvae'
data_path: 'data/CAVIAR-o.pkl.gz'
experiment_name: 'vggbit_cvae'
canonical_split: True
model_type: cvae
n_epochs: 200
val_check_period: 64 #32
patience: 1000
n_trials: 10
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
n_hidden_units: 8 #8
batch_size: 8
learning_rate: 0.1
beta1: 0.9
beta2: 0.999
epsilon: 1.0e-8
conv_dropout: 0.0
fc_dropout: 0.0
vgg_fc_layer_size: 512
cvae_fc_layer_size: 512