dataset: CAVIAR-o # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-o/cvae'
data_path: 'data/CAVIAR-o.pkl.gz'
experiment_name: 'vggbit_cvae'
canonical_split: True
model_type: cvae
n_epochs: 200
val_check_period: 128 #32
patience: 1000
n_trials: 50
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters