dataset: CAVIAR-c # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-c'
data_path: 'data//CAVIAR-c.pkl.gz'
loss: cosine # possible choices : cosine, von_mises, mad, vm_likelihood
experiment_name: 'vggbit_cosine'
canonical_split: True
predict_kappa: False
fixed_kappa_value: 10.0
n_epochs: 50
val_check_period: 32
conv_dropout: 0.2
fc_dropout: 0.5
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters
n_trials: 20