dataset: CAVIAR-c # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/CAVIAR-c'
data_path: 'data//CAVIAR-c.pkl.gz'
experiment_name: 'vggbit_cvae'
canonical_split: True
n_epochs: 50
val_check_period: 32
conv_dropout: 0.2
fc_dropout: 0.5
n_trials: 20
n_hidden_units: 8
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
batch_sizes: [8]
learning_rates: [0.001]