dataset: IDIAP # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/IDIAP/pan'
data_path: 'data//IDIAP.pkl'
loss: vm_likelihood # possible choices : cosine, von_mises, mad, vm_likelihood
experiment_name: 'vggbit_likelihood_fixed_kappa'
canonical_split: True
predict_kappa: False
fixed_kappa_value: 60.0
n_epochs: 5
val_check_period: 64
conv_dropout: 0.2
fc_dropout: 0.5
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
batch_sizes: [128]
learning_rates: [1.0e-1]
n_trials: 1