experiment_name: 'vggbit_likelihood'
dataset: IDIAP
root_log_dir: 'logs/IDIAP/pan'
data_path: 'data//IDIAP.pkl'
canonical_split: True
net_output: pan # possible choices: pan, tilt, roll
loss: vm_likelihood # possible choices : cosine, von_mises, mad, vm_likelihood
predict_kappa: True
fixed_kappa_value: 10.0
n_epochs: 20
batch_sizes: [64]
learning_rates: [1.0e-7]
n_trials: 10