experiment_name: 'vggbit_cosine'
root_log_dir: 'logs/IDIAP/roll'
data_path: 'data//IDIAP.pkl'
canonical_split: True
net_output: roll # possible choices: pan, tilt, roll
loss: cosine # possible choices : cosine, von_mises, mad, vm_likelihood
predict_kappa: False
fixed_kappa_value: 1.0
n_epochs: 20
batch_sizes: [256]
learning_rates: [1.0e-1]
n_trials: 10