dataset: IDIAP # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/IDIAP'
data_path: 'data//IDIAP.pkl'
experiment_name: 'vggbit_cvae'
canonical_split: True
n_epochs: 100
val_check_period: 32
n_trials: 10
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
n_hidden_units: 2
batch_sizes: [32]
epsilons: [1.0e-8]
learning_rates: [0.001]
beta1: [0.95]
conv_dropout: 0.2
fc_dropout: 0.5