dataset: IDIAP # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/IDIAP/pan/vm_mixture'
data_path: 'data//IDIAP.pkl'
experiment_name: 'vggbit_vmmix_best'
canonical_split: True
model_type: vm_mixture
loss_type: vm_likelihood
fixed_kappa_value: 10
n_epochs: 1000
val_check_period: 64 #32
patience: 200
n_trials: 50
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters