dataset: IDIAP # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/IDIAP/pan'
data_path: 'data//IDIAP.pkl'
loss: vm_likelihood # possible choices : cosine, von_mises, mad, vm_likelihood
experiment_name: 'vggbit_likelihood_search'
canonical_split: True
predict_kappa: True
fixed_kappa_value: 10.0
n_epochs: 10
val_check_period: 64
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters
n_trials: 50
