dataset: IDIAP # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # possible choices: pan, tilt, roll
root_log_dir: 'logs/IDIAP'
data_path: 'data//IDIAP.pkl'
experiment_name: 'vggbit_cvae'
canonical_split: True
n_epochs: 100
val_check_period: 64
patience: 5 # number of epochs with no imrpovement before train will be stopped
n_trials: 50
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters
n_hidden_units: 8
batch_sizes: [64]
learning_rates: [0.0001]
beta1: [0.9]
conv_dropout: 0.2
fc_dropout: 0.5
vgg_fc_layer_size: 512
cvae_fc_layer_size: 512