dataset: TownCentre # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/TownCentre/cvae'
data_path: 'data/TownCentre.pkl.gz'
experiment_name: 'vggbit_cvae_best'
canonical_split: True
model_type: cvae
n_epochs: 1000
val_check_period: 128 #32
patience: 1000
n_trials: 5
random_hyp_search: False #if True, ignore config params and perform random search of hyperparameters
n_hidden_units: 8 #8
batch_size: 32
learning_rate: 0.001
beta1: 0.99
beta2: 0.999
epsilon: 1.0e-7
conv_dropout: 0.2
fc_dropout: 0.5
vgg_fc_layer_size: 512
cvae_fc_layer_size: 512