dataset: TownCentre # TownCentre, IDIAP, CAVIAR-o, CAVIAR-c
net_output: pan # make sense for IDIAP only, possible choices: pan, tilt, roll
root_log_dir: 'logs/TownCentre/cosine'
data_path: 'data/TownCentre.pkl.gz'
experiment_name: 'vggbit_cosine_best'
canonical_split: True
model_type: bivgg
loss_type: cosine
n_epochs: 1000
val_check_period: 128 #32
patience: 50
n_trials: 50
random_hyp_search: True #if True, ignore config params and perform random search of hyperparameters
batch_size: 32
learning_rate: 0.001
beta1: 0.9
beta2: 0.999
epsilon: 1.0e-7
conv_dropout: 0.2
fc_dropout: 0.5
vgg_fc_layer_size: 512
cvae_fc_layer_size: 512